### ISSUE TITLE
アルゴリズムを分離

### ISSUE THREAD

**Issue by infrub** [tube-worm/ppasumi#21]
/algorithm/asumialg00.py
とかにアルゴリズムを分離．
引数および帰り値の形式は共通して[datetime bidopen ... askclose sema ... tradeflag] なるpandas.Dataframeにして、
ただし引数の時は最新の列はaskcloseまでしか貰わず(貰えず)それにsema ... tradeflagを計算して付け加えたのを返す
でmain.pyは更新のたびに最新のaskcloseまでの値をつけてalgorithmを呼びtradeflagまで計算してもらってそれを基準にエントリーする
単独のpandas.Dataframeを持ち回すのでメモリも食わないはず
backtestも新しくそれを利用する形のを作る(既存のほうが速度は全く上なのでquickbacktestみたいな名前で残す)

**Comment by tube-worm** [comment]
merged.
